From Stdlib Require Import Utf8.
From SmallInversion Require Import small_inversion.

From Stdlib Require Import Fin.

(* This is an alternative definition for the lesser than or equal relation on natural numbers.
 Here, both indices can be used to invert. *)
Inductive le2 : nat -> nat -> Prop :=
| L0 : forall m, le2 0 m
| LS : forall n m, le2 n m -> le2 (S n) (S m).


Definition FAKE := Prop.

(*By default, the Derive InvProxy command will invert on both.*)

Unset Elimination Schemes.

Derive InvProxy for le2.

Set Elimination Schemes.


(* However, in some cases, this is too much for what we want.
 In this lemma, the first index of le2 is a variable and can't be inverted upon,
 -- an ordinary pattern-matching should be used there.
 We get an error message "Not an inductive definition" (technically,
 this is because the term to be analyzed by pattern-matching is
 not reduced to a partial inductive type).
 *)

Lemma le2_n_1_small n : le2 n 1 -> n = 0 \/ n = 1.
Proof.
  intro l.
  Fail sinv l.
Abort.

(* Let us restart just before the definition of FAKE. *)
Reset FAKE.

(* We then need a more precise version of inversion, that can be obtained using
   the inductive type inversion_pattern that specifies a relevant pattern of indices. *)
Print pilotInversion.

(* It is used after the keywords "with pattern x" in the command
   "Derive InvProxy", where x is a closed term of type inversion_pattern.
   The term (pilotInversion n l) indicates that we ask for an inversion on index
   number n, where l is a list that recursively specifies the kind of pattern matching
   to be performed deeper for this index. Note that the length of list must be exactly
   the nummber of partial inductive types, and that the index position must take parameters
   into account.
   In our example, the desired proxy is generated by the following command.
 *)
Unset Elimination Schemes.
Derive InvProxy for le2
  with pattern(pilotInversion 1 [noInversion; pilotInversion 1 [noInversion; noInversion]]).
Set Elimination Schemes.

Lemma le2_n_1_small n : le2 n 1 -> n = 0 \/ n = 1.
Proof.
  intro l.
  sinv l as [ | n l'].
  - left; reflexivity.
  - right; sinv l'; reflexivity.
Qed.

(* As finding the correct pattern can be tricky, we also provide the command
   "create_sinv_call y" that, for a given inductively typed term y, prints
   an invocation to "Derive InvProxy" with a suitable pattern for this y.
   It can only be used in interactive proof mode.
   Let us restart just before the definition of FAKE again. *)

Reset FAKE.

Lemma le2_n_1_small n : le2 n 1 -> n = 0 \/ n = 1.
Proof.
  intro l.
  create_sinv_call l.
  (* We get :
Derive InvProxy for le2 with pattern (pilotInversion 1 [noInversion; pilotInversion 1 [noInversion; noInversion]]).
   *)
Abort.

Unset Elimination Schemes.
Derive InvProxy for le2 with pattern (pilotInversion 1 [noInversion; pilotInversion 1 [noInversion; noInversion]]).
Set Elimination Schemes.

Lemma le2_n_1_small n : le2 n 1 -> n = 0 \/ n = 1.
Proof.
  intro l.
  sinv l as [ | n l'].
  - left; reflexivity.
  - right; sinv l'; reflexivity.
Qed.
