(** A tutorial on automated proxy-based small inversions (PBSI) *)

(** First, get the plugin for PBSI *)

From SmallInversion Require Import small_inversion.

(* ================================================================== *)
(** * Basics *)

(** Proxy-based small inversions derive specialised versions of an
inductive type $T$ according to the values (more precisely, the
patterns) of the inductive indices of $T$, so that filtering on a term
of type $T$ takes into account its particular form, i.e., the
constructors used in its indices.

They work in two steps:

- First, defining suitable partial inductive types, which mimic the
  original inductive type $T$ depending on constructors used for one
  or more of its indices. A mapping from $T$ to the new partial
  inductive types is also defined. The partial inductive types
  together with this mapping act as a proxy for $T$.  This step only
  needs to be performed once.

- Second, inverting a object. It consists in decomposing a relevant
  proxy for it, using the `destruct` tactic (in interactive mode) or a
  pattern matching (when defining a dependently typed functional
  program).

Both of those steps are supported by automated tools, the first by
various commands that customise the specialisation of the original
inductive type into partial inductive types, the second in the form of
tactics to be called in interactive mode.
*)

(* ==================================================================
*) (** * Chapter 1: using PBSI in interactive proof mode *)

(** Here, PBSI is used as an alternative to the well-known inversion
    tactic *)

(** ** An explainable inversion of even *)

Inductive even : nat -> Prop :=
| even0 : even 0
| even2 : forall (n : nat), even n -> even (S (S n)).

(** Inversion is needed when we have assumptions (even X), where X is
    not a variable but, for instance O, (S O), (S (S ...)) *)

(** The following comand is needed in order to have PBSI for even.
    Its effect is to define some auxiliary inductive types derived
    from the definition of even, as well as a proxy function for even
    called even_proxy (by default).  "Unset/Set Elimination Schemes"
    is not mandatory, it justs makes the output cleaner.  *)

Unset Elimination Schemes (* For comfort *).
Derive InvProxy for even.
Set Elimination Schemes (* For comfort *).

(** You can then replace "inversion" by our tactic "sinv". *)
Lemma even_cancel_S_S_draft n : even (S (S n)) -> even n.
Proof. intro e. sinv e. exact H. Qed.

(** A better practice is to have an explicit name for the H above.
    The syntax is the same as for destruct *)
Lemma even_cancel_S_S n : even (S (S n)) -> even n.
Proof. intro e. sinv e as [e']. exact e'. Qed.

(** An absurd hypothesis *)
Lemma no_even_1 : even 1 -> False.
Proof. intro e. sinv e. Qed.

(** A more interesting lemma, where an induction on even is followed
    by an inversion *)
Lemma even_plus_cancel n m : even n -> even (n + m) -> even m.
Proof.
  induction 1 as [ | n en Hen]; cbn; intro enm.
  - exact enm.
  - (* inversion needed*)
    sinv enm as [enm']. exact (Hen enm').
Qed.

(** Explanation *)
(** Reminder : the argument even is called an index
    (we have an indiced family of types) *)
Lemma even_cancel_S_S_explain n : even (S (S n)) -> even n.
Proof.
  intro e.
  (** We have the assumption   e : even (S (S n)).
      By pattern-matching on the *index*, we know that only
      the second constructor of even is possible.
      The special cases of even x where x has the shape (S (S n))
      are precisely gathered in even_S_S, one of the auxiliary inductive
      types generated by the above command "Derive InvProxy for even." *)
  Print even_S_S.
  (** Result (up to a renaming, possibly):
  Inductive even_S_S (n : nat) : Prop :=
  | even2_S_S : even n -> even_S_S n. *)

  (** We also have (see below) :  even (S (S n) -> even_S_S n.
      A proof term for this implication is provided by invproxy. *)
  Check (invproxy e : even_S_S n).
  (** Actually, sinv e is nothing else than destruct (invproxy e).
      A case analysis on (invproxy e) will then keep the only
      relevant case, corresponding to the constructor even2.
      A more technical remark that can be ignored at first reading:
      as n is a parameter of even_S_S, it is not a component of
      even2_S_S, in contrast with even2; we then do not write
      "as [n' e']" but just "as [e']", so that we kepp the link
      with n in the conclusion of the goal *)
  destruct (invproxy e) as [e'].
  (** In summary, "sinv e" is nothing lese than a shortcut for
      "destruct (invproxy e)" *)
  exact e'.
Qed.

Lemma no_even_1_explanation : even 1 -> False.
Proof.
  intro e.
  (** Here, we have no case of even x where x has the shape (S O) *)
  Print even_S_O.
  (** We also have :  even (S O) -> even_S_O. *)
  Check (invproxy e : even_S_O).
  (** Consistently, destruct (invproxy e) generates no case to consider *)
  destruct (invproxy e).
Qed.

(**
   The command "Derive InvProxy for even." also generates a
   proxy for even, named "even_proxy", which is itself registered
   as in instance of a Rocq class, so that sinv uses the proxy
   the the relevant relation.
   You can print even_proxy. You could then redefine it in a moe
   readable manner as follows, starting wit its type. *)

Definition even_proxy_type n :=
  match n with
  | 0 => even_O
  | 1 => even_S_O
  | S (S n) => even_S_S n
  end.

(** Handcrafted version of even_proxy *)
Definition my_even_proxy {n} (e : even n) : even_proxy_type n :=
  match e with
  | even0 => even0_O
  | even2 n x => even2_S_S n x
  end.

(** Then observe on the following scenario that you get a
    reasonably explicit and explainable proof of even_cancel_S_S,
    in contrast with what you would get with "inversion" *)
Lemma even_cancel_S_S_handcrafted n : even (S (S n)) -> even n.
Proof.
  intro e.
  Check (my_even_proxy e).
  Eval cbn in (even_proxy_type (S (S n))).
  Check (my_even_proxy e : even_S_S n).
  destruct (my_even_proxy e) as [e'].
  exact e'.
Qed.


(** ** Inversion on a single index of a binary relation *)

(** Examples with a binary relation R, with an assumption R x y
    where x is known but y is free.
    Indices are numbered from 0 : 0, 1, ...
    Then we will use Derive InvProxy for R with index 0.  *)

(** We start with a very simple relation *)

Inductive color := Red | Orange | Green.

Inductive nextcolor : color -> color -> Prop :=
| ncGO : nextcolor Green Orange
| ncOR : nextcolor Orange Red
| ncRG : nextcolor Red Green.

Unset Elimination Schemes (* For comfort *).
Derive InvProxy for nextcolor with index 0.
Set Elimination Schemes (* For comfort *).

Theorem nextcolor3 : forall c1 c2 c3 c4,
    nextcolor c1 c2 -> nextcolor c2 c3 ->  nextcolor c3 c4 ->
    c4 = c1.
Proof.
  intros c1 c2 c3 c4 nc1 nc2 nc3.
  (* We have 3 cases for the first assumption, forcing c2 to
  have a fixed value. *)
  destruct nc1 as [ | | ].
  - (* Only 1 case is left for nc2, provided we use (small) inversion;
       in turn, c3 becomes constrained to be a specific value *)
    sinv nc2.
    (** Explanation *)
    Undo.
    Check (invproxy nc2 : nextcolor_Orange c3).
    Print nextcolor_Orange.
    destruct (invproxy nc2).
    (* Similarly for nc3 *)
    sinv nc3. reflexivity.
   (* The remaining subgoals are proved in the same way *)
  - sinv nc2; sinv nc3; reflexivity.
  - sinv nc2; sinv nc3; reflexivity.
Qed.

(** Now we consider a more advanced example:
    the semantics of well-typed expressions.
    This example is the source language provided in a famous
    paper by Mc Carthy and Painter, 1967. *)

(* Internalized Basic Types *)
Variant ty : Set := Nat | Bool.

Definition value t : Set :=
  match t with
  | Bool => bool
  | Nat => nat
  end.

(* Untyped expressions *)
Inductive exp : Set :=
| Val t (v : value t) : exp
| Plus (e1 e2 : exp) : exp
| Ifte (b : exp) (e1 e2 : exp) : exp.

Inductive well_typed : exp -> ty -> Prop :=
| WTVal t (v : value t) : well_typed (Val t v) t
| WTPlus (e1 e2 : exp) :
  well_typed e1 Nat -> well_typed e2 Nat ->
  well_typed (Plus e1 e2) Nat
| WTIfte (eb : exp) (e1 e2 : exp) (t : ty) :
  well_typed eb Bool -> well_typed e1 t -> well_typed e2 t ->
  well_typed (Ifte eb e1 e2) t.

Unset Elimination Schemes (* For comfort *).
Derive InvProxy for well_typed with index 0.
Set Elimination Schemes (* For comfort *).

(** A semantics of well-typed expressions can be defined by recursion
    on expressions, then small inversion on well-typing.
    Note that here, both the tactic inversion and dependent
    elimination of Equations fail (complicated workarounds are
    possible, anyway PBSI behaves much better. *)
Module Script.

#[refine]
Fixpoint semE {t} (e : exp) : well_typed e t -> value t :=
  match e with
  | Val t' v => fun w =>
      _
  | Plus e1 e2 => fun w =>
      _
  | Ifte eb e1 e2 => fun w =>
      _
  end.
- sinv w. exact v.
- Fail inversion w.
  sinv w as [w1 w2].
  exact (semE _ e1 w1 + semE _ e2 w2).
- sinv w as [wb w1 w2].
  exact (if semE _ eb wb then semE _ e1 w1 else semE _ e2 w2).
Defined.

End Script.

(** Note that defining a function that can be used later in the statement
    of theorems is BAD PRACTICE, because the very meaning of such theorems
    comes from the very body of the program that defines the function.
    In this case semE, can be used to state the correctness of a compiler.
    But the above definition uses tactics, whereas the tactic languqge
    is NOT in the TCB of Rocq.
    Fortunately PBSI can be used directly.
    First, we can use "invprox w" with additional information *)

(** Advanced usage of PBSI, with classes *)
Fixpoint semE {t} (e : exp) : well_typed e t -> value t :=
  match e with
  | Val t' v => fun w =>
      let 'WTVal_Val _ _ in well_typed_Val _ _ t := invproxy w
      return value t in v
  | Plus e1 e2 => fun w =>
      let 'WTPlus_Plus _ _ w1 w2 in well_typed_Plus _ _ t := invproxy w
      return value t in
      semE e1 w1 + semE e2 w2
  | Ifte eb e1 e2 => fun w =>
      let (wb, w1, w2) := invproxy w : well_typed_Ifte eb e1 e2 t in
      if semE eb wb then semE e1 w1 else semE e2 w2
  end.

(** Second, we can refine our own proxy function, so that the code
    is even more explicit *)

Module HandCrafted.

Definition well_typed_dispatch e : ty -> Prop :=
  match e with
  | Val t v => well_typed_Val t v
  | Plus e1 e2 => well_typed_Plus e1 e2
  | Ifte eb e1 e2 => well_typed_Ifte eb e1 e2
  end.

Definition well_typed_sinv {e t} (w : well_typed e t) : well_typed_dispatch e t :=
  match w with
  | WTVal t w =>  WTVal_Val t w
  | WTPlus e1 e2 w1 w2 => WTPlus_Plus e1 e2 w1 w2
  | WTIfte eb e1 e2 t wb w1 w2 => WTIfte_Ifte eb e1 e2 t wb w1 w2
  end.

Fixpoint semE {t} (e : exp) : well_typed e t -> value t :=
  match e with
  | Val t' v => fun w =>
      let 'WTVal_Val _ _ in well_typed_Val _ _ t := well_typed_sinv w 
      return value t in v
  | Plus e1 e2 => fun w =>
      let 'WTPlus_Plus _ _ w1 w2 in well_typed_Plus _ _ t := well_typed_sinv w
      return value t in
      semE e1 w1 + semE e2 w2
  | Ifte eb e1 e2 => fun w =>
      let (wb, w1, w2) := well_typed_sinv w : well_typed_Ifte eb e1 e2 t in
      if semE eb wb then semE e1 w1 else semE e2 w2
  end.

End HandCrafted.

(* ================================================================== *)
(** * Chapter 2: using PBSI in dependtly typed functions *)

(* ================================================================== *)
(** * Chapter 3: tuning PBSI *)

(* ================================================================== *)
(** * Chapter 4: making your developement independent from our plugin *)
